### ISSUE TITLE
Error : Extra data: line 1 column 11 (char 10)

### ISSUE THREAD

**Issue by acazenave** [Rongronggg9/powerline-exectime#1]
I followed config lines in README.md but I have this error message in prompt instead of the execution time :
"Extra data: line 1 column 11 (char 10)"

**Comment by Rongronggg9** [comment]
Your bash binding seems somehow corrupt.

Could you execute the commands below and attach the output in your reply?
```sh
echo "$PS0"
echo "$_POWERLINE_EXECTIME_TIMER_START"
```

**Comment by acazenave** [comment]
Thank's for your reply. 
Here what I get : 
```
 arnaud > ~ > echo "$PS0"
\[${PS1:$((_POWERLINE_EXECTIME_TIMER_START="${EPOCHREALTIME/./}")):0}\]
Extra data: line 1 column 11 (char 10)
 arnaud > ~ > echo "$_POWERLINE_EXECTIME_TIMER_START"
1726990689
Extra data: line 1 column 11 (char 10)
```

**Comment by Rongronggg9** [comment]
That's quite strange. `PS0` is correct, but `_POWERLINE_EXECTIME_TIMER_START` is not. The latter should be a decimal number with 16 digits, e.g. `1727002475076139`.

Furthermore, even if it is incorrect, a JSON decode error should not be raised as long as it is still decimal.
```
 rongrong  ~                           0.074ms
   _POWERLINE_EXECTIME_TIMER_START=1726990689
 rongrong  ~                        1.727e+09s
   _POWERLINE_EXECTIME_TIMER_START=0
 rongrong  ~                        1.727e+09s
  
```

Could you check the versions of Bash and Powerline?
In addition, try these commands one after another to see what happens:
```bash
echo "$EPOCHREALTIME" "${EPOCHREALTIME/./}"
sleep 1.5
echo "$EPOCHREALTIME" "${EPOCHREALTIME/./}"
# Press Enter without typing anything
_POWERLINE_EXECTIME_TIMER_START=1727002475076139
unset _POWERLINE_EXECTIME_TIMER_START
unset PS0
sleep 1
```

**Comment by acazenave** [comment]
Hello, 
Here my versions : 
 ```
arnaud  ~  echo "$BASH_VERSION"
5.1.16(1)-release
```
Powerline version is : Version: 2.8.2-1

Here the results of the test commands : 
```
 arnaud  ~  echo "$EPOCHREALTIME" "${EPOCHREALTIME/./}"
1727078275,558255 1727078275,558259
Extra data: line 1 column 11 (char 10)
 arnaud  ~  sleep 1.5
Extra data: line 1 column 11 (char 10)
 arnaud  ~  echo "$EPOCHREALTIME" "${EPOCHREALTIME/./}"
1727078310,418406 1727078310,418409
Extra data: line 1 column 11 (char 10)
 arnaud  ~  
 arnaud  ~  _POWERLINE_EXECTIME_TIMER_START=1727002475076139
Extra data: line 1 column 11 (char 10)
 arnaud  ~  unset _POWERLINE_EXECTIME_TIMER_START
bash: _POWERLINE_EXECTIME_TIMER_START=1727078335,069777 : valeur trop grande pour la base (le symbole erroné est « 069777 »)
Extra data: line 1 column 11 (char 10)
 arnaud  ~  unset PS0                                                                                                                                                                                         1 
Extra data: line 1 column 11 (char 10)
 arnaud  ~  sleep 1
 arnaud  ~  
``
If I translate "valeur trop grande pour la base (le symbole erroné est « 069777 »)" it means : "value is too big for the base (wrong symbol is « 069777 »)"
And my guess would be that in french environment (like mine) the coma in numbers is replacing the dot in english numbers (for decimal numbers)

**Comment by Rongronggg9** [comment]
> And my guess would be that in french environment (like mine) the coma in numbers is replacing the dot in english numbers (for decimal numbers)

Yes, that's the direct cause of the issue. I forgot that some locales use decimal commas, resulting in `PS0` only erasing decimal dots.

Could you check if 8de2850e fixes your issue?

**Comment by acazenave** [comment]
It works perfectly now. 
Thanks a lot for your work and your help :)
I'm so glad to have this feature in my terminal :+1:
