### ISSUE TITLE
Having hard time with installation into bash

### ISSUE THREAD

**Issue by gczajkowskiTT** [Rongronggg9/powerline-exectime#3]
Every command now has this error 
> ls
bash: _POWERLINE_EXECTIME_TIMER_START=: syntax error: operand expected (error token is "=")

**Comment by Rongronggg9** [comment]
Could you provide more information about your bash?

```bash
bash --version
echo $BASH_VERSION
echo $EPOCHREALTIME
echo $PS0
echo $PS1
```

**Comment by gczajkowskiTT** [comment]
I cannot issue any commands because of the error. But if I add this to `~/.bashrc` then
```
GNU bash, version 4.4.20(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
4.4.20(1)-release

\[${PS1:$((_POWERLINE_EXECTIME_TIMER_START="${EPOCHREALTIME/[^0-9]/}")):0}\]
[\u@\h \W]\$
```
After starting the shell all commands are broken
```
ls
bash: _POWERLINE_EXECTIME_TIMER_START=: syntax error: operand expected (error token is "=")
```

**Comment by Rongronggg9** [comment]
Oops, Bash 4 is outdated. `EPOCHREALTIME` is only available on Bash 5+, and Bash 5 was released 5 years ago.

I will see if I can support both...

**Comment by Rongronggg9** [comment]
Does 045cf1bbf9678d98aab5735ab12f200d07492a24 fix the issue?

**Comment by gczajkowskiTT** [comment]
I followed the new instructions, and functionality has improved! The segment is added; however, the times reported are very strange. `ls` takes a random number of minutes and seconds. It seems there is some kind of scaling factor. If I run something that takes minutes, it shows up as hours. It seems to be off by a hundred?

PS This is the initial
`_POWERLINE_EXECTIME_TIMER_START=1731300747246125251`

**Comment by Rongronggg9** [comment]
That's quite strange. Could you try the below commands and show their output? 

```bash
echo "$PS0"
echo "${BASH_VERSINFO[*]}"
echo start "$_POWERLINE_EXECTIME_TIMER_START" stop "$_POWERLINE_EXECTIME_TIMER_STOP"
_powerline_exectime_at_stop; echo start "$_POWERLINE_EXECTIME_TIMER_START" stop "$_POWERLINE_EXECTIME_TIMER_STOP"
echo start "$_POWERLINE_EXECTIME_TIMER_START" stop "$_POWERLINE_EXECTIME_TIMER_STOP"
echo start "$_POWERLINE_EXECTIME_TIMER_START" stop "$_POWERLINE_EXECTIME_TIMER_STOP"
```

And what's your Python version? (If you have multiple installations of Python, choose the one that runs powerline-daemon)

**Comment by gczajkowskiTT** [comment]
<img width="1446" alt="image" src="https://github.com/user-attachments/assets/88139422-250b-4759-a2b7-96b88b280d30">

**Comment by gczajkowskiTT** [comment]
python3.11 and I am 80% confident powerline is running it.

**Comment by Rongronggg9** [comment]
It seems that every time difference is multiplied by 1000. This should not happen as I implemented timestamp unit guesser in 045cf1bbf9678d98aab5735ab12f200d07492a24 and the only possible way (assuming your RTC works fine) to trigger this is using an outdated powerline-exectime.

Did you update the `powerline-exectime` package (i.e., `pythonX.Y -m pip install -U git+https://github.com/Rongronggg9/powerline-exectime` or `git pull && pythonX.Y -m pip install -U .`) and restart the powerline daemon (i.e., `systemctl --user restart powerline-daemoe.service` or simply restart your computer)?

**Comment by gczajkowskiTT** [comment]
Success! Thank you so much! Restarting the daemon was pivotal.

```
pip3 install -U git+https://github.com/Rongronggg9/powerline-exectime --force-reinstall
python3.11 $HOME/.local/bin/powerline-daemon --replace
```
PS. The overhead of all the processing going on in powerline, bash, powerline-exectime is about 170ms per command as  `sleep 1`  shows 1170ms, but I don't need any more level of accuracy. 

This actually tells me how long it takes to render the powerline, which is a terrific bonus feature! Mine is particularly slow with all the segments I have enabled, and I'm looking for ways to make it faster without sacrificing removing segments.

**Comment by Rongronggg9** [comment]
> `sleep 1`  shows 1170ms, but I don't need any more level of accuracy.

`sleep 1` only guarantees that it sleeps for **at least** 1 second. The accuracy depends on the kernel and the system load. It always takes more than 1 second to return. `time sleep 1` measures the time taken by `sleep 1` more precisely.

> PS. The overhead of all the processing going on in powerline, bash, powerline-exectime is about 170ms per command

> This actually tells me how long it takes to render the powerline, which is a terrific bonus feature! Mine is particularly slow with all the segments I have enabled, and I'm looking for ways to make it faster without sacrificing removing segments.

If you would like to measure the "base overhead" more precisely, just execute the empty command `:`.

The overhead of powerline-exectime is about 0.x ms on Bash 5 and 1~10ms (depends on CPU performance and system load) on Bash 4. It **is** measured in the exectime segment.

However, the overhead of powerline rendering **is not** measured, as the timer is stopped before calling powerline. This is intended, as powerline-exectime aims to measure the execution time of commands executed as precise as possible.

Thus, most of your mentioned "overhead" may not be related to powerline. Did you set up some additional prompting utilities other than powerline? You can check them by executing `echo "$PROMPT_COMMAND"`.

**Comment by gczajkowskiTT** [comment]
> time sleep 1 measures the time taken by sleep 1 more precisely.

Yep, and that shows barely any overhead
```
bash -c '/usr/bin/time sleep 1'
        1.01 real         0.00 user         0.00 sys
```
>If you would like to measure the "base overhead" more precisely, just execute the empty command :

Excellent trick. It shows 18ms overhead. However, the "feel" of the terminal's responsiveness is now exceptionally slow. This is on Linux. I bet on my MacOS, and it will be a lot faster. 

> The overhead of powerline-exectime is about 0.x ms on Bash 5 and 1~10ms (depends on CPU performance and system load) on Bash 4. It is measured in the exectime segment

That's good to know! It will be another reason for our team to push for the next version of the OS. 

> However, the overhead of powerline rendering is not measured, as the timer is stopped before calling powerline. This is intended, as powerline-exectime aims to measure the execution time of commands executed as precise as possible.

I appreciate the explanation.

> Did you set up some additional prompting utilities other than powerline? 

Yes quite a few and hence the slowness: Bash-PreExec for Atuin, Powerline, direnv, Atuin 

> You can check them by executing echo "$PROMPT_COMMAND".
```
> echo $PROMPT_COMMAND 
__bp_precmd_invoke_cmd _powerline_status_wrapper _powerline_set_prompt _direnv_hook;printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}" : __bp_interactive_mode
```

**Comment by gczajkowskiTT** [comment]
I am going a bit wild testing all the segments

<img width="1912" alt="image" src="https://github.com/user-attachments/assets/ed8a2502-1ba0-404d-a4d7-354a0a300de1">
